import { writeFile } from 'node:fs/promises';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import 'dotenv/config';
import { AgentWallet, HelixClient, VPBuilder } from '@helix-id/sdk-js';
import type { SignedVP, UnsignedVP } from '@helix-id/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const exampleRoot = dirname(__dirname);
const walletPath = join(exampleRoot, 'agent', 'wallet.enc');
const fixturePath = join(exampleRoot, 'fixtures', 'vp.json');

const helixApiUrl = process.env.HELIX_API_URL ?? process.env.API_BASE_URL ?? 'http://localhost:3000';
const platformUrl = process.env.BOOKING_PLATFORM_URL ?? 'http://localhost:3001';
const targetService = process.env.HELIX_TARGET_SERVICE ?? 'amazon';
const walletPassphrase = process.env.WALLET_PASSPHRASE ?? 'change-this-passphrase';
const userDID = 'did:hedera:testnet:user-demo-traveler';

type WalletVC = {
  id: string;
  validUntil: string;
  credentialSubject: {
    privilegeScopes: string[];
  };
};

type Action = {
  label: string;
  route: string;
  deniedLine?: string;
  templateDeniedLine?: string;
  successLine: (body: unknown) => string;
};

let fixtureSaved = false;

function encodeSignedVP(signedVP: SignedVP): string {
  return Buffer.from(JSON.stringify(signedVP), 'utf8').toString('base64url');
}

async function callPlatform(route: string, signedVP: SignedVP): Promise<{ status: number; body: unknown }> {
  const response = await fetch(`${platformUrl}${route}`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      Authorization: `Bearer ${encodeSignedVP(signedVP)}`,
    },
    body: JSON.stringify({ requestedAt: new Date().toISOString() }),
  });

  return {
    status: response.status,
    body: await response.json(),
  };
}

async function buildFreshVP(client: HelixClient, agentDid: string, privateKeyHex: string, vcId: string): Promise<{ signedVP: SignedVP; vpId: string }> {
  // A fresh VP template is needed for every action because the vpId is single-use,
  // the nonce is fresh, and the target service binding is part of the signed payload.
  const template = await client.createVPTemplate({
    agentDid,
    userDid: userDID,
    targetService,
    vcType: 'HelixAgentCredential',
    vcId,
  });

  console.log(`        -> VP template received: ${template.vpId} (single-use)`);

  // Signing happens locally through the SDK's Ed25519 VP builder. The private key
  // is loaded from the encrypted wallet and never transmitted to Helix ID or the platform.
  return {
    signedVP: await new VPBuilder(template.unsignedVP as UnsignedVP).sign(privateKeyHex, `${agentDid}#key-1`),
    vpId: template.vpId,
  };
}

async function saveFixtureOnce(signedVP: SignedVP, vpId: string): Promise<void> {
  if (fixtureSaved) return;
  fixtureSaved = true;
  await writeFile(
    fixturePath,
    `${JSON.stringify({
      _comment: 'Real signed VP generated by examples/e2e-travel-concierge. The embedded StatusList URL points to the Helix ID instance that issued it, so verification requires that same instance or equivalent persisted state.',
      vpId,
      signedVP,
    }, null, 2)}\n`,
    'utf8',
  );
  console.log(`        -> Saved signed VP fixture to ${fixturePath}`);
}

async function runAction(client: HelixClient, agentDid: string, privateKeyHex: string, vcId: string, action: Action): Promise<void> {
  console.log(`\n[Agent] ${action.label}`);
  console.log('        -> Requesting VP template');
  let signedVP: SignedVP;
  let vpId: string;
  try {
    const fresh = await buildFreshVP(client, agentDid, privateKeyHex, vcId);
    signedVP = fresh.signedVP;
    vpId = fresh.vpId;
  } catch (error) {
    const code = error && typeof error === 'object' && 'code' in error ? String((error as { code: unknown }).code) : 'VP_TEMPLATE_FAILED';
    console.log(`        <- DENIED (${code})`);
    if (action.templateDeniedLine) {
      console.log(`        ${action.templateDeniedLine}`);
    }
    return;
  }
  console.log('        -> Signing VP locally with Ed25519; private key not transmitted');
  await saveFixtureOnce(signedVP, vpId);
  console.log('        -> Presenting to booking platform');

  const result = await callPlatform(action.route, signedVP);
  if (result.status >= 200 && result.status < 300) {
    console.log(`        <- GRANTED. ${action.successLine(result.body)}`);
    return;
  }

  const error = result.body && typeof result.body === 'object' && 'error' in result.body
    ? String((result.body as { error: unknown }).error)
    : `HTTP_${result.status}`;
  console.log(`        <- DENIED (${error})`);
  if (action.deniedLine) {
    console.log(`        ${action.deniedLine}`);
  }
}

async function waitForRevocation(vcId: string): Promise<void> {
  const rl = createInterface({ input, output });
  console.log('\n[Agent] Waiting for agent owner to revoke credential.');
  console.log('        In a real system, the owner revokes from their admin console.');
  console.log('        Revocation takes effect on the next VP verification because Helix ID checks VC status each time.');
  console.log('\nRun this command, then press Enter:\n');
  console.log(`curl -X POST ${helixApiUrl}/v1/vcs/${vcId}/revoke \\`);
  console.log('  -H "x-admin-api-key: $HELIX_ADMIN_API_KEY"');
  await rl.question('\nPress Enter after revocation...');
  rl.close();
}

async function main(): Promise<void> {
  // The wallet contains the agent DID, public key, encrypted private key, and
  // issued credentials. Loading decrypts the private key inside this process only.
  const wallet = await new AgentWallet().load(walletPassphrase, walletPath);
  const credential = wallet.credentials.at(-1);
  if (!credential) throw new Error('Wallet has no credentials');
  const vc = JSON.parse(credential.vcJson) as WalletVC;

  console.log(`[Agent] Loaded wallet for ${wallet.did}`);
  console.log(`[Agent] Credential expires at ${vc.validUntil}`);

  // This demo hardcodes the user DID. In production it would come from the
  // user DID verification flow before the agent acts on the user's behalf.
  console.log(`[Agent] Simulated authenticated user: ${userDID}`);

  const client = new HelixClient(helixApiUrl);

  await runAction(client, wallet.did, wallet.privateKeyHex, credential.vcId, {
    label: 'Searching flights to London...',
    route: '/flights/search',
    successLine: () => 'Found 12 flights.',
  });

  await runAction(client, wallet.did, wallet.privateKeyHex, credential.vcId, {
    label: 'Searching hotels in London...',
    route: '/hotels/search',
    successLine: () => 'Found 2 hotels.',
  });

  await runAction(client, wallet.did, wallet.privateKeyHex, credential.vcId, {
    label: 'Booking flight BOM-LHR...',
    route: '/flights/book',
    successLine: () => 'Flight booking confirmed.',
  });

  await runAction(client, wallet.did, wallet.privateKeyHex, credential.vcId, {
    label: 'Booking hotel - The Langham...',
    route: '/hotels/book',
    successLine: () => 'Hotel booking confirmed.',
    deniedLine: 'I can search hotels, but I am not authorised to book them.',
  });

  await waitForRevocation(credential.vcId);

  await runAction(client, wallet.did, wallet.privateKeyHex, credential.vcId, {
    label: 'Booking another flight after revocation...',
    route: '/flights/book',
    successLine: () => 'Flight booking confirmed.',
    templateDeniedLine: 'My credential has been revoked, so Helix ID will not issue a fresh presentation template.',
    deniedLine: 'My credential has been revoked, so the platform no longer trusts this presentation.',
  });
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
