import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AgentWallet, HelixClient, VPBuilder } from '@helix-id/sdk-js';
import type { SignedVP, UnsignedVP } from '@helix-id/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const exampleRoot = dirname(__dirname);
const walletPath = join(exampleRoot, 'agent', 'wallet.enc');
const fixturePath = join(exampleRoot, 'fixtures', 'vp.json');

const helixApiUrl = process.env.HELIX_API_URL ?? process.env.API_BASE_URL ?? 'http://localhost:3000';
const targetService = process.env.HELIX_TARGET_SERVICE ?? 'amazon';
const walletPassphrase = process.env.WALLET_PASSPHRASE ?? 'change-this-passphrase';
const userDID = 'did:hedera:testnet:user-demo-traveler';

async function main(): Promise<void> {
  const wallet = await new AgentWallet().load(walletPassphrase, walletPath);
  const credential = wallet.credentials.at(-1);
  if (!credential) throw new Error('Wallet has no credentials');
  const client = new HelixClient(helixApiUrl);

  const template = await client.createVPTemplate({
    agentDid: wallet.did,
    userDid: userDID,
    targetService,
    vcType: 'HelixAgentCredential',
    vcId: credential.vcId,
  });

  // This fixture VP is intentionally not presented to any verifier. That keeps
  // its vpId unconsumed for examples/verify-vp.ts and examples/self-verify.ts.
  const signedVP: SignedVP = await new VPBuilder(template.unsignedVP as UnsignedVP).sign(
    wallet.privateKeyHex,
    `${wallet.did}#key-1`,
  );

  await writeFile(
    fixturePath,
    `${JSON.stringify({
      _comment: 'Real signed VP generated by examples/e2e-travel-concierge. This VP is intentionally not presented by the fixture script, so its vpId remains unconsumed until a verifier example uses it. The embedded StatusList URL points to the Helix ID instance that issued it.',
      vpId: template.vpId,
      signedVP,
    }, null, 2)}\n`,
    'utf8',
  );

  console.log(`[Agent] Wrote unconsumed signed VP fixture: ${fixturePath}`);
  console.log(`[Agent] vpId: ${template.vpId}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
