// e2e travel/agent/create vp fixture
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AgentWallet, VPBuilder } from '@helix-id/sdk-js';
import type { SignedVC, SignedVP } from '@helix-id/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const exampleRoot = dirname(__dirname);
const walletPath = join(exampleRoot, 'agent', 'wallet.enc');
const fixturePath = join(exampleRoot, 'fixtures', 'vp.json');

const targetService = process.env.HELIX_TARGET_SERVICE ?? 'amazon';
const walletPassphrase = process.env.WALLET_PASSPHRASE ?? 'change-this-passphrase';
const userDID = 'did:hedera:testnet:user-demo-traveler';

async function main(): Promise<void> {
  const walletStore = new AgentWallet();
  const wallet = await walletStore.load(walletPassphrase, walletPath);
  const credential = await walletStore.getLatestCredential({ vcType: 'HelixAgentCredential' }, walletPassphrase, walletPath);
  if (!credential) throw new Error('Wallet has no credentials');
  const vc = JSON.parse(credential.vcJson) as SignedVC;

  const signedVP: SignedVP = await new VPBuilder({
    vc,
    holderDid: wallet.did,
    userDid: userDID,
    targetService,
  }).sign(
    wallet.privateKeyHex,
    `${wallet.did}#key-1`,
  );

  await writeFile(
    fixturePath,
    `${JSON.stringify({
      _comment: 'Real signed VP generated by examples/e2e-travel-concierge. This VP is intentionally not presented by the fixture script, so its vpId remains unconsumed until a verifier example uses it. The embedded StatusList URL points to the Helix ID instance that issued it.',
      vpId: signedVP.id,
      signedVP,
    }, null, 2)}\n`,
    'utf8',
  );

  console.log(`[Agent] Wrote unconsumed signed VP fixture: ${fixturePath}`);
  console.log(`[Agent] vpId: ${signedVP.id}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
